### ISSUE TITLE
Run only one instance

### ISSUE THREAD

**Issue by yz778** [hunkydoryrepair/MonitorKeeper#3]
Check to ensure there is only one running instance when launching.

That small feature request aside, THANK YOU for making this amazing app! Works perfectly on latest Windows 10 (20H2 as of this ticket).

I have a triple monitor setup, my main is connected via DisplayPort. So previously, each time I turned off/on my monitors my windows would go all over the place. Now with your app, everything stays put and I can't imagine using my computer without it.

**Comment by hunkydoryrepair** [comment]
fixed
