### ISSUE TITLE
Minimized Windows

### ISSUE THREAD

**Issue by as2-0** [hunkydoryrepair/MonitorKeeper#4]
When a Window of an application was maximized and has been minimzed to the taskbar afterwards.
After Windows dis- and reconnecting the displays while using this tool, the Window of the minimzed application isn't maximized any more, when you open it again.

I hope the description was understandable.

Except this small issue this tool is amazing. Eventhough it's a shame that Windows doesn't seem to offer such a feature.
Thanks for making it!!!

(I'm using Windows 10 1909 with 2 identical monitors connected via DisplayPort)

**Comment by hunkydoryrepair** [comment]
I've heard Microsoft is addressing this window problem in Windows 11. 

This is an interesting issue. There is a flag on the Windowplacement structure that tells windows whether to restore the minimized windows to MAXIMIZED or not. Unfortunately, I don't think applications can READ that setting. I'll look into it a little.

**Comment by hunkydoryrepair** [comment]
This is actually just a bug in MonitorKeeper. The flag was being overwritten. Building a fix

**Comment by hunkydoryrepair** [comment]
new release ready with this fixed.
