### ISSUE TITLE
Task Manager window

### ISSUE THREAD

**Issue by jgassie** [hunkydoryrepair/MonitorKeeper#5]
Thank you for this application!
For some reason, on one of my newer Win10 setups with 2 DP outputs, the Task Manager window (taskmgr.exe) will always move from Monitor 2 to Monitor 1 upon awakening, but so far all of the other Windows applications for that system stay on the appropriate monitor (thanks to MonitorKeeper).
Do you have any ideas why Task Manager wouldn't be retained?  Thank you!

**Comment by hunkydoryrepair** [comment]
You probably need to run MonitorKeeper as administrator. It can’t move admin applications unless running as admin.

**Comment by jgassie** [comment]
That makes sense, thank you!  I later noticed that the CMD prompt wouldn't
move as well, and it was running as admin.. thank you!

Regards, Jerry
