### ISSUE TITLE
Notes : repositioning of windows 

### ISSUE THREAD

**Issue by yuyuishiishi** [hunkydoryrepair/MonitorKeeper#7]
it takes a few seconds for My PC to recognizes the 2nd extended display, when coming back from the sleep mode. 
Therefore sometimes the repositioning of the windows failed in my PC.

In this case, repositioning of windows should be after the PC recognize the 2nd display.
in order to achieve this, TimerCallback function should be delayed as below and it worked fine for me.

//
// reposition windows after a slight delay
VOID CALLBACK TimerCallback(
	_In_ HWND     hwnd,
	_In_ UINT     uMsg,
	_In_ UINT_PTR idEvent,
	_In_ DWORD    dwTime
)
{
	Sleep(5 * 1000); // Inserted to delay TimerCallback function 
	ProcessMonitors();
	KillTimer(hwnd, idEvent);
}

**Comment by hunkydoryrepair** [comment]
did you close this because your solution worked for you? Or was the timer unnecessary after all?

MonitorKeeping watches for the monitors to be recognized and repositions only after the 2nd monitor is detected, so it isn't clear to me why adding a delay would be necessary.
